manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/Samdasoo1076
  projects:
    - name: zmkfirmwares
      remote: zmkfirmware
      revision: example
      import: config/west.yml
  self:
    path: config