manifest:
  remotes:
    - name: zmk-config
      url-base: https://github.com/Samdasoo1076
  projects:
    - name: zmk-config
      remote: zmk-config
      revision: main
      import: config/west.yml
